apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  labels:
    app: my-board-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-board-app
  template:
    metadata:
      labels:
        app: my-board-app
    spec:
      containers:
      - name: boardshack
        image: praveendevops95/boardshack
        ports:
        - containerPort: 8080







